cinst PowerShell
cinst git.install
cinst SublimeText2
cinst nodejs.install
cinst putty
cinst filezilla
cinst fiddler
cinst paint.net
cinst NuGet.CommandLine
cinst NugetPackageManager
cinst Compass
cinst winmerge